networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  # Zabbix
  db:
    image: postgres:16-alpine
    container_name: zbx-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: StrongZbxPass123
      TZ: Europe/Moscow
    volumes:
      - zbx-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zbx-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: StrongZbxPass123
      TZ: Europe/Moscow
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.6

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zbx-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: StrongZbxPass123
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [labnet]

  # Центральный сервер логов через rsyslog (RELP+TLS)
  log-srv:
    build: ./rsyslog
    container_name: log-srv
    hostname: log-srv
    ports:
      - "6514:6514"
    volumes:
      - rsyslog-logs:/var/log/remote
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/server/log-srv.crt:/etc/rsyslog/certs/log-srv.crt:ro
      - ./rsyslog/certs/server/log-srv.key:/etc/rsyslog/certs/log-srv.key:ro
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.8

  # Веб-серверы с Nginx + Zabbix Agent2 + rsyslog client
  webserver1:
    build: ./web
    image: lab/webserver:latest
    container_name: webserver1
    hostname: webserver1
    networks:
      labnet:
        ipv4_address: 172.30.0.11
    ports:
      - "8081:80"
    volumes:
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/web1/client.crt:/etc/rsyslog/certs/client.crt:ro
      - ./rsyslog/certs/web1/client.key:/etc/rsyslog/certs/client.key:ro
    restart: unless-stopped

  webserver2:
    build: ./web
    image: lab/webserver:latest
    container_name: webserver2
    hostname: webserver2
    networks:
      labnet:
        ipv4_address: 172.30.0.12
    ports:
      - "8082:80"
    volumes:
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/web2/client.crt:/etc/rsyslog/certs/client.crt:ro
      - ./rsyslog/certs/web2/client.key:/etc/rsyslog/certs/client.key:ro
    restart: unless-stopped

  # Splunk
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Str0ng!Splunk#123
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.7

  uf-web1:
    build: ./uf
    image: lab/uf:latest
    container_name: uf-web1
    hostname: webserver1
    depends_on:
      - splunk
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.21

  uf-web2:
    build: ./uf
    image: lab/uf:latest
    container_name: uf-web2
    hostname: webserver2
    depends_on:
      - splunk
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.22

volumes:
  zbx-pgdata:
  splunk-var:
  splunk-etc:
  rsyslog-logs:
