networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  # Запускаем сервис для создания TSL-сертификатов для каждого хоста
  certs-init:
    image: alpine:3.20
    container_name: certs-init
    working_dir: /work/rsyslog/certs
    command:
      - /bin/sh
      - -exc
      - |
        set -Eeuo pipefail
        apk add --no-cache openssl bash
        ls -la .
        test -f ./make-certs.sh || { echo "make-certs.sh not found"; exit 2; }
        chmod +x ./make-certs.sh
        ./make-certs.sh
    environment:
      FORCE: "1"
    volumes:
      - ./rsyslog/certs:/work/rsyslog/certs
    restart: "no"
    mem_limit: 1g
    cpus: "0.8"

  # Zabbix
  db:
    image: postgres:16-alpine
    container_name: zbx-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - zbx-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.5
    mem_limit: 2g
    cpus: "1.0"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zbx-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.6
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: [ "CMD-SHELL", "pgrep zabbix_server >/dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 180s
    mem_limit: 1500m
    cpus: "1.0"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zbx-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${TZ}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [labnet]
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -X POST -H 'Content-Type: application/json-rpc' \
             -d '{\"jsonrpc\":\"2.0\",\"method\":\"apiinfo.version\",\"id\":1,\"params\":[]}' \
             http://localhost:8080/api_jsonrpc.php | grep -q '\"result\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    mem_limit: 2g
    cpus: "1.0"

  zbx-settings:
    build: ./zbx-settings
    container_name: zbx-settings
    depends_on:
      zabbix-server:
        condition: service_healthy
      zabbix-web:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1
      ZBX_API_URL: ${ZBX_API_URL}
      ZBX_USER: ${ZBX_USER}
      ZBX_PASS: ${ZBX_PASS}
      ZBX_LANG: ${ZBX_LANG}
      WAIT_TIMEOUT: ${WAIT_TIMEOUT}
      WAIT_INTERVAL: ${WAIT_INTERVAL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    networks:
      labnet:
    restart: "no"
    mem_limit: 2g
    cpus: "1.0"

  zbx-agent-plugins:
    build: ./plugins
    container_name: zbx-agent-plugins
    hostname: monitoring-plugins
    depends_on:
      - zabbix-server
      - log-srv
    volumes:
      - ./plugins:/externalscripts-src:ro
      - rsyslog-logs:/var/log/remote:ro
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.31
    mem_limit: 200m
    cpus: "0.20"

  # Центральный сервер логов через rsyslog (RELP+TLS)
  log-srv:
    depends_on:
      certs-init:
        condition: service_completed_successfully
    build: ./rsyslog
    container_name: log-srv
    hostname: log-srv
    ports:
      - "6514:6514"
    volumes:
      - rsyslog-logs:/var/log/remote
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/server/log-srv.crt:/etc/rsyslog/certs/log-srv.crt:ro
      - ./rsyslog/certs/server/log-srv.key:/etc/rsyslog/certs/log-srv.key:ro
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.8
    mem_limit: 256m
    cpus: "0.20"

  # Веб-серверы с Nginx + Zabbix Agent2 + rsyslog client
  webserver1:
    depends_on:
      certs-init:
        condition: service_completed_successfully
    build: ./web
    image: lab/webserver:latest
    container_name: webserver1
    hostname: webserver1
    networks:
      labnet:
        ipv4_address: 172.30.0.11
    ports:
      - "8081:80"
    volumes:
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/web1/client.crt:/etc/rsyslog/certs/client.crt:ro
      - ./rsyslog/certs/web1/client.key:/etc/rsyslog/certs/client.key:ro
      - web1-logs:/var/log
    restart: unless-stopped
    #mem_limit: 224m
    #cpus: "0.15"

  webserver2:
    depends_on:
      certs-init:
        condition: service_completed_successfully
    build: ./web
    image: lab/webserver:latest
    container_name: webserver2
    hostname: webserver2
    networks:
      labnet:
        ipv4_address: 172.30.0.12
    ports:
      - "8082:80"
    volumes:
      - ./rsyslog/certs/ca/ca.crt:/etc/rsyslog/certs/ca.crt:ro
      - ./rsyslog/certs/web2/client.crt:/etc/rsyslog/certs/client.crt:ro
      - ./rsyslog/certs/web2/client.key:/etc/rsyslog/certs/client.key:ro
      - web2-logs:/var/log
    restart: unless-stopped
    #mem_limit: 224m
    #cpus: "0.15"

  # Splunk
  splunk:
    build: ./splunk
    container_name: splunk
    environment:
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
      SPLUNK_HOME_OWNERSHIP_ENFORCEMENT: "false"
      DEBUG: "true"
      ANSIBLE_EXTRA_FLAGS: "-vv"
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - splunk-var:/opt/splunk/var
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.7
    mem_limit: 3560m
    cpus: "2.0"

  uf-web1:
    build: ./uf
    image: lab/uf:latest
    container_name: uf-web1
    hostname: webserver1
    depends_on:
      - splunk
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.21
    volumes:
      - web1-logs:/web-logs:ro
    environment:
      SPLUNK_PASSWORD: ${UF_PASSWORD}
      SPLUNK_HOME_OWNERSHIP_ENFORCEMENT: "false"
    mem_limit: 1600m
    cpus: "1.0"

  uf-web2:
    build: ./uf
    image: lab/uf:latest
    container_name: uf-web2
    hostname: webserver2
    depends_on:
      - splunk
    restart: unless-stopped
    networks:
      labnet:
        ipv4_address: 172.30.0.22
    volumes:
      - web2-logs:/web-logs:ro
    environment:
      SPLUNK_PASSWORD: ${UF_PASSWORD}
      SPLUNK_HOME_OWNERSHIP_ENFORCEMENT: "false"
    mem_limit: 1600m
    cpus: "1.0"

volumes:
  zbx-pgdata:
  splunk-var:
  splunk-etc:
  rsyslog-logs:
  web1-logs:
  web2-logs:
